#!/usr/bin/env bash

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until `.macos` has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# Disable reminder for default handler
defaults write ch.sudo.cyberduck "defaulthandler.reminder" -bool false

# Show files with '.'
defaults write ch.sudo.cyberduck "browser.showHidden" -bool true

# Always use default editor
defaults write ch.sudo.cyberduck "editor.alwaysUseDefault" -bool true

# Use SFTP as default protocol
defaults write ch.sudo.cyberduck "connection.protocol.default" -string "sftp-iterate GmbH"

# Check for updates automatically
defaults write ch.sudo.cyberduck SUEnableAutomaticChecks -int 1
defaults write ch.sudo.cyberduck "update.check" -bool true

# Do not send profile info
defaults write ch.sudo.cyberduck SUSendProfileInfo -int 0

# Finish setup
killall "Cyberduck" &> /dev/null
