#!/usr/bin/env bash

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until `.macos` has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# Notifications disabled
defaults write com.sequelpro.SequelPro GrowlEnabled -int 0

# Keywords are in uppercase automatically
defaults write com.sequelpro.SequelPro CustomQueryAutoUppercaseKeywords -int 1

# Check for updates automatically
defaults write com.sequelpro.SequelPro SUEnableAutomaticChecks -int 1

# Do not send profile info
defaults write com.sequelpro.SequelPro SUSendProfileInfo -int 0

# Finish setup
killall "SequelPro" &> /dev/null
