#!/usr/bin/env bash

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until `.macos` has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# Prefered language
defaults write com.torusknot.SourceTreeNotMAS AppleLanguages -array "en"

# Disallow Sourcetree to modify your global Mercurial and Git configuration files
defaults write com.torusknot.SourceTreeNotMAS agreedToUpdateConfig -int 0

# Allow force push
defaults write com.torusknot.SourceTreeNotMAS allowForcePush -int 1

# Delete stash after successul apply
defaults write com.torusknot.SourceTreeNotMAS applyStashAndDelete -int 1

# Project folder
defaults write com.torusknot.SourceTreeNotMAS defaultFolder -string "$HOME/github"

# Prune tracking branches no longer present on remote(s) on fetch
defaults write com.torusknot.SourceTreeNotMAS gitFetchPrune -int 1

# Automatically check for updates
defaults write com.torusknot.SourceTreeNotMAS SUEnableAutomaticChecks -int 1

# Finish setup
killall "Sourcetree" &> /dev/null
